### ISSUE TITLE
Unhandled RegexpError when commit body contains symbol characters

### ISSUE THREAD

**Issue by brian-onyando** [bkuhlmann/git-lint#8]
## Overview
git-lint fails with an error if the commit body contains symbol characters `:`, `[` and `]`

```
/home/user/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:57:in `body_without_trailers': empty range in char class: /Issue : [sc-12].*/m (RegexpError)
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:48:in `body_without_comments'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:44:in `body_without_trailing_spaces'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:35:in `step_c_body_lines'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:27:in `block in build'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:27:in `each'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:27:in `build'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:21:in `block in call'
        from <internal:kernel>:90:in `tap'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:21:in `call'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/entry.rb:14:in `call'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/history.rb:38:in `block in call'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/history.rb:38:in `map'
        from /home/brian/.gem/ruby/3.1.2/gems/git_plus-1.3.2/lib/git_plus/parsers/commits/saved/history.rb:38:in `call'
        from /home/brian/.rubies/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `commits'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/lib/git/lint/commits/systems/local.rb:11:in `call'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/lib/git/lint/commits/loader.rb:25:in `call'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/lib/git/lint/analyzer.rb:45:in `call'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/lib/git/lint/cli/actions/analyze/branch.rb:29:in `parse'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/lib/git/lint/cli/actions/analyze/branch.rb:18:in `call'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/lib/git/lint/cli/shell.rb:34:in `perform'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/lib/git/lint/cli/shell.rb:23:in `call'
        from /home/brian/.gem/ruby/3.1.2/gems/git-lint-4.2.0/exe/git-lint:6:in `<top (required)>'
        from /home/brian/.gem/ruby/3.1.2/bin/git-lint:25:in `load'
        from /home/brian/.gem/ruby/3.1.2/bin/git-lint:25:in `<main>'

```
## Steps to Recreate
- Create a commit with the following subject and body
 ```
Add some changes

Issue : [sc-12]
```
- execute `git-lint --analyze`
## Environment
```
OS: Ubuntu 20.04.4 LTS
Ruby: 3.1.2
git-lint: 4.2.0
```

**Comment by bkuhlmann** [comment]
Hey Brian. :wave: Thanks for reporting this. This was due to a regular expression parsing issue with the [Git+](https://www.alchemists.io/projects/git_plus) gem. I've fixed the issue and released [Version 1.4.0](https://www.alchemists.io/projects/git_plus/versions).

Git Lint will pick up the new Git+ version automatically if you do a `bundle update`. You can also forcibly install the latest Git+ gem version if you want as well. If you are using CI or GitHub Actions, this will happen automatically for you.

Anyway, this is fixed now so I'm going to close this issue. :bow:
